namespace: flux-system

resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: phoban01/cue-controller
  newName: ghcr.io/phoban01/cue-controller
  newTag: v0.0.1-alpha.2
