# permissions for end users to view cueinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cueinstance-viewer-role
rules:
- apiGroups:
  - cue.contrib.flux.io
  resources:
  - cueinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cue.contrib.flux.io
  resources:
  - cueinstances/status
  verbs:
  - get
