namespace: flux-system
resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- cluster_admin_role_binding.yaml

namePrefix: cue-
